controller_list:
  - name: fake_i5aubo1_controller
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_hand_controller
    joints:
      - gripper_finger1_joint